model_list:
  - model_name: groq-llama3
    litellm_params:
      model: groq/llama3-8b-8192
      api_key: os.environ/GROQ_API_KEY
  - model_name: cerebras-llama3
    litellm_params:
      model: cerebras/llama3-70b-instruct
      api_key: os.environ/CEREBRAS_API_KEY

litellm_settings:
  set_verbose: True
